apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: grafana
  app.kubernetes.io/part-of: grafana

bases:
  - ./argo-dashboards/
  - ./jupyterhub-dashboards/
  - ./kafka-dashboards/

resources:
- datasource.yaml
- grafana.yaml
