---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: data-science-pipelines

bases:
  - ../../base

resources:
  # Roles
  - ./roles/kubeflow-pipelines-metadata-writer-role.yaml

  # Rolebindings
  - ./rolebindings/kubeflow-pipelines-metadata-writer-binding.yaml

  # ServiceAccounts
  - ./serviceaccounts/kubeflow-pipelines-metadata-writer.yaml
  - ./serviceaccounts/metadata-grpc-server.yaml

  # Deployments
  - ./deployments/metadata-envoy-deployment.yaml
  - ./deployments/metadata-grpc-deployment.yaml
  - ./deployments/metadata-writer.yaml

  # Services
  - ./services/metadata-envoy-service.yaml
  - ./services/metadata-grpc-service.yaml
  
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: metadata-envoy
    newName: gcr.io/ml-pipeline/metadata-envoy
    newTag: 1.7.0
  - name: metadata-grpc
    newName: gcr.io/tfx-oss-public/ml_metadata_store_server
    newTag: 1.0.0
  - name: metadata-writer
    newName: quay.io/internaldatahub/metadata-writer
    newTag: 1.1.0
