apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: ailibrary
  app.kubernetes.io/part-of: ailibrary

generatorOptions:
  disableNameSuffixHash: true
