---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: data-science-pipelines

bases:
  - ../../base

resources:
  # Configmaps
  - ./configmaps/ds-pipeline-config.yaml
  - ./configmaps/pipeline-install-config.yaml

  # Deployments
  - ./secrets/mlpipeline-minio-artifact.yaml
  - ./secrets/mysql-secret.yaml

generatorOptions:
  disableNameSuffixHash: true
