apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opendatahub
resources:
- job.yaml
- role.yaml
- role-binding.yaml
- service-account.yaml

commonLabels:
  component.opendatahub.io/name: pachyderm
  opendatahub.io/component: "true"
  app.kubernetes.io/part-of: pachyderm

configMapGenerator:
- name: pachyderm-deployer-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true

# vars:
# - name: pachyderm_version
#   objref:
#     kind: ConfigMap
#     name: pachyderm_parameters
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.pachyderm_version
# configurations:
# - params.yaml
