---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: data-science-pipelines

bases:
  - ../../base

resources:
  # ServiceAccounts
  - ./serviceaccounts/mysql.yaml

  # PersistentVolumeClaims
  - ./persistentvolumeclaims/mysql-pv-claim.yaml

  # Deployments
  - ./deployments/mysql.yaml

  # Services
  - ./services/mysql.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: mysql
    newName: gcr.io/ml-pipeline/mysql
    newTag: "5.7"
